= pkg.appcat.composition.objectstorage.cloudscale

The parent key for all of the following parameters is `pkg.appcat.composition.objectstorage.cloudscale`.

== `secretNamespaces:objectsusers`

[horizontal]
type:: string
default:: `provider-cloudscale-secrets-objectsusers`

The namespace where the provider-cloudscale stores intermediate credential `Secrets` for `ObjectUser` resources.
The idea is to have them in their own namespace so that they don't clutter any other namespace.
In the composition the `Secrets` are being used for creating S3 Buckets on cloudscale.ch in `Bucket` resources.

== `bucketDeletionPolicy`

[horizontal]
type:: enum
values:: `[DeleteAll, DeleteIfEmpty]`
default:: `DeleteAll`

The behavior what to do with the bucket and its data when the user deletes the claim.

With `DeleteIfEmpty`, the bucket can only be deleted if all objects within are deleted as well (empty bucket).
If there are objects, the `Bucket` resource won't be removed until the bucket is emptied.

With `DeleteAll`, all objects in the bucket are recursively and deleted.
Once all objects are deleted the bucket (and the `Bucket` resource) are removed.
