= pkg.appcat.composition.objectstorage.exoscale

The parent key for all of the following parameters is `pkg.appcat.composition.objectstorage.exoscale`.

== `secretNamespaces:iamkeys`

[horizontal]
type:: string
default:: `provider-exoscale-secrets-iamkeys`

The namespace where the provider-exoscale stores intermediate credential `Secrets` for `IAMKKeys` resources.
The idea is to have them in their own namespace so that they don't clutter any other namespace.
In the composition the `Secrets` are being used for accessing S3 Buckets on exoscale.com.

== `bucketDeletionPolicy`

[horizontal]
type:: enum
values:: `[DeleteAll, DeleteIfEmpty]`
default:: `DeleteAll`

The behavior what to do with the bucket and its data when the user deletes the claim.

With `DeleteIfEmpty`, the bucket can only be deleted if all objects within are deleted as well (empty bucket).
If there are objects, the `Bucket` resource won't be removed until the bucket is emptied.

With `DeleteAll`, all objects in the bucket are recursively deleted.
Once all objects are deleted the bucket (and the `Bucket` resource) are removed.
