{
 "title": "VSHN Crossplane",
 "tags": [
  "AppCat",
  "schedar"
 ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values({cluster_id=~\".*user-workload\"},cluster_id)"
    }
   },
   { "name": "datname", "label": "Database", "query": { "query": "label_values(datname)" } },
   {
    "name": "Provider",
    "query": {
     "query": "label_values(workqueue_work_duration_seconds_bucket,job)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Important note",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# IMPORTANT\n\n<b>After each change please export this dashboard as JSON and update it in component-appcat repository</b>"
   }
  },
  {
   "title": "How long in seconds processing an item from workqueue takes for $Provider",
   "type": "heatmap",
   "description": "The time it takes from the moment the job start until it finish (either successfully or with an error).",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by (le) (rate(workqueue_work_duration_seconds_bucket{job=\"$Provider\", cluster_id=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Length of time per reconciliation per controller $Provider",
   "type": "heatmap",
   "description": "Length of time per reconciliation per controller\t",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum by (le) (rate(controller_runtime_reconcile_time_seconds_bucket{job=\"$Provider\", cluster_id=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests statistics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true
  },
  {
   "title": "Reconcilliation Rate of Crossplane resources with error (including providers)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "irate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", container=\"crossplane\", result=\"error\"}[5m])",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "irate(controller_runtime_reconcile_total{cluster_id=\"$cluster\", container=\"package-runtime\", result=\"error\"}[5m])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "heatmap, request latency for reconciliation of Function-Appcat",
   "type": "heatmap",
   "description": "darker = less\nbrighter =more",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "sum by (le) (rate(composition_run_function_seconds_bucket{function_name=\"function-appcat\", cluster_id=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of crossplane total amount of reconciliations",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\"}[5m]) > 0 ",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Sum of rates crossplane total amount of reconciliations",
   "type": "timeseries",
   "description": "This panel shows overall change and distribution of amount of reconciliations",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "sum(rate(controller_runtime_reconcile_total{cluster_id=\"$cluster\",container=\"crossplane\"}[5m]))",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Heatmap of webhook latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "sum by(le) (rate(controller_runtime_webhook_latency_seconds_bucket{cluster_id=\"$cluster\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Rate of total webhook requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "rate(controller_runtime_webhook_requests_total{cluster_id=\"$cluster\",container=\"crossplane\"}[5m])",
     "legendFormat": "{{code}} {{webhook}}"
    }
   ]
  },
  { "title": "Resources available", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Crossplane resource exists",
   "type": "timeseries",
   "description": "The number of managed resources that exist",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "crossplane_managed_resource_exists{cluster_id=\"$cluster\"}",
     "legendFormat": "{{gvk}}"
    }
   ]
  },
  {
   "title": "Crossplane resource synced",
   "type": "timeseries",
   "description": "The number of managed resources in Synced=True state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "crossplane_managed_resource_synced{cluster_id=\"$cluster\",}",
     "legendFormat": "{{gvk}}"
    }
   ]
  },
  {
   "title": "Unsynced resources",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crossplane_managed_resource_exists{cluster_id=\"$cluster\"} - crossplane_managed_resource_synced{cluster_id=\"$cluster\"} ",
     "legendFormat": "{{gvk}}"
    }
   ]
  },
  {
   "title": "Crossplane resource ready",
   "type": "timeseries",
   "description": "The number of managed resources in Ready=True state",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "crossplane_managed_resource_ready{cluster_id=\"$cluster\"}",
     "legendFormat": "{{gvk}}"
    }
   ]
  },
  {
   "title": "Unready resources",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 57 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "crossplane_managed_resource_exists{cluster_id=\"$cluster\"} - crossplane_managed_resource_ready{cluster_id=\"$cluster\"}",
     "legendFormat": "{{gvk}}"
    }
   ]
  }
 ]
}