{
 "title": "VSHNKeycloak",
 "description": "Dashboard of Keycloak metrics exported with Keycloak Metrics SPI\r\n\r\nhttps://github.com/aerogear/keycloak-metrics-spi",
 "tags": [ "Appcat" ],
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{service=\"VSHNKeycloak\"},cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{cluster_id=\"$cluster\", service=\"VSHNKeycloak\"},namespace)"
    }
   },
   {
    "name": "instance_namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster_id=\"$cluster\", label_appuio_io_billing_name=\"appcat-keycloak\", label_appcat_vshn_io_claim_namespace=\"$namespace\"},namespace)"
    }
   },
   { "name": "Datasource", "query": "Prometheus AppCat" }
  ]
 },
 "panels": [
  {
   "title": "Important note",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# IMPORTANT\n\n<b>After each change please export this dashboard as JSON and update it in component-appcat repository</b>"
   }
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_max_bytes{namespace=\"$instance_namespace\"})",
     "legendFormat": "MAX"
    },
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$instance_namespace\"})",
     "legendFormat": "USED"
    }
   ]
  },
  {
   "title": "Average Load in last minute (1m interval)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "base_cpu_systemLoadAverage{namespace=\"$instance_namespace\"}",
     "legendFormat": "{{__name__}}"
    }
   ]
  },
  {
   "title": "Current Memory nonHEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$instance_namespace\", container=\"keycloak\", area=\"nonheap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$instance_namespace\" ,container=\"keycloak\", area=\"nonheap\"})"
    }
   ]
  },
  {
   "title": "Current Memory HEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$instance_namespace\", container=\"keycloak\", area=\"heap\"})*100/sum(jvm_memory_max_bytes{namespace=\"$instance_namespace\" ,container=\"keycloak\", area=\"heap\"})"
    }
   ]
  },
  {
   "title": "Current Memory HEAP + nonHEAP",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{namespace=\"$instance_namespace\", container=\"keycloak\"})*100/sum(jvm_memory_max_bytes{namespace=\"$instance_namespace\" ,container=\"keycloak\"})"
    }
   ]
  },
  {
   "title": "CPU percentage usage",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(base_cpu_systemLoadAverage{namespace=\"$instance_namespace\",container=\"keycloak\"}/base_cpu_availableProcessors{namespace=\"$instance_namespace\", container=\"keycloak\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "current number of classes loaded in the Java Virtual Machine (JVM)",
   "type": "timeseries",
   "description": "Meaning: It shows how many Java classes are currently loaded into memory by the JVM’s class loader.\nWhy it matters:\nA high or steadily increasing value may indicate classloader leaks or excessive dynamic class generation.\nMonitoring this metric helps detect memory issues related to class loading/unloading.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 25 },
   "targets": [
    {
     "expr": "jvm_classes_loaded_classes{namespace=\"$instance_namespace\"}",
     "legendFormat": "number of classes"
    }
   ]
  },
  {
   "title": "Active threads currently running",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "jvm_threads_live_threads{namespace=\"$instance_namespace\"}",
     "legendFormat": "live Keycloak threads"
    }
   ]
  }
 ]
}