{
 "title": "Galera/MariaDB - Overview",
 "description": "mariadb galera cluster overview. metrics from mysqld exporter.",
 "tags": [
  "mysql",
  "galera",
  "mariadb",
  "Appcat"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filters" },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{service=\"VSHNMariaDB\"},cluster_id)"
    }
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{cluster_id=\"$cluster\", service=\"VSHNMariaDB\"},namespace)"
    }
   },
   {
    "name": "name",
    "query": {
     "query": "label_values(appcat_probes_seconds_count{cluster_id=\"$cluster\", namespace=\"$namespace\", service=\"VSHNMariaDB\"},name)"
    }
   },
   {
    "name": "instance_namespace",
    "query": {
     "query": "label_values(kube_namespace_labels{cluster_id=\"$cluster\", label_kubernetes_io_metadata_name=~\".*$name.*\", label_appcat_vshn_io_claim_namespace=\"$namespace\"},namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# IMPORTANT\n\n<b>After each change please export this dashboard as JSON and update it in component-appcat repository</b>"
   }
  },
  {
   "title": "Service Status",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "mysql_up{namespace=\"vshn-mariadb-mariadb-widera-bh4t9\"}"
    }
   ]
  },
  {
   "title": "Service Uptime",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "targets": [
    {
     "expr": "mysql_global_status_uptime{namespace=\"$instance_namespace\"}"
    }
   ]
  },
  {
   "title": "Instances",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 7, "x": 8, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min by (pod) (mysql_galera_status_info{namespace=~\"$instance_namespace\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "WSREP Sequence Number",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 9, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "max by(pod) (mysql_global_status_wsrep_last_committed{namespace=\"$instance_namespace\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Queries per Second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(mysql_global_status_queries{namespace=~\"$instance_namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by(pod) (container_memory_working_set_bytes{namespace=\"$instance_namespace\",container=\"mariadb-galera\"})",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "min by (pod) (kube_pod_container_resource_limits_memory_bytes{namespace=\"$instance_namespace\",container=\"mariadb-galera\"})",
     "legendFormat": "Limit {{ pod }}"
    },
    {
     "expr": "max by(pod) (container_memory_rss{namespace=\"$instance_namespace\",container=\"mariadb-galera\"})",
     "legendFormat": "RSS {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum by (pod)(rate(container_cpu_usage_seconds_total{namespace=\"$instance_namespace\",container=\"mariadb-galera\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    },
    {
     "expr": "kube_pod_container_resource_limits_cpu_cores{namespace=\"$instance_namespace\",container=\"mariadb-galera\"}",
     "legendFormat": "Limit {{ pod }}"
    }
   ]
  },
  {
   "title": "WSREP Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(mysql_global_status_wsrep_replicated{namespace=\"$instance_namespace\"}[$__rate_interval]))",
     "legendFormat": "Sent Q/s {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(mysql_global_status_wsrep_replicated_bytes{namespace=\"$instance_namespace\"}[$__rate_interval]))",
     "legendFormat": "Sent Bytes/s {{ pod }}"
    },
    {
     "expr": "sum by (pod) (rate(mysql_global_status_wsrep_received{namespace=\"$instance_namespace\"}[$__rate_interval]))",
     "legendFormat": "Received Q/s {{pod}}"
    },
    {
     "expr": "sum by (pod) (rate(mysql_global_status_wsrep_received_bytes{namespace=\"$instance_namespace\"}[$__rate_interval]))",
     "legendFormat": "Received Bytes/s {{ pod }}"
    }
   ]
  },
  {
   "title": "WSREP Queue",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (mysql_global_status_wsrep_local_send_queue{namespace=\"$instance_namespace\"})",
     "legendFormat": "Send queue {{pod}}"
    },
    {
     "expr": "sum by (pod) (mysql_global_status_wsrep_local_receive_queue{namespace=\"$instance_namespace\"})",
     "legendFormat": "Recv queue {{ pod }}"
    },
    {
     "expr": "sum by (pod) (mysql_global_status_wsrep_flow_control_recv{namespace=\"$instance_namespace\"})",
     "legendFormat": "Flow control recv {{ pod }}"
    },
    {
     "expr": "sum by (pod) (mysql_global_status_wsrep_flow_control_sent{namespace=\"$instance_namespace\"})",
     "legendFormat": "Flow control sent {{ pod }}"
    }
   ]
  },
  {
   "title": "WSREP Pause",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by (pod) (mysql_global_status_wsrep_flow_control_paused{namespace=\"$instance_namespace\"})",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "WSREP Desyncs",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(mysql_global_status_wsrep_desync_count{namespace=\"$instance_namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "Mysql Connections",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (mysql_global_status_threads_connected{namespace=~\"$instance_namespace\"})",
     "legendFormat": "Current - {{ pod }}"
    },
    {
     "expr": "min by (namespace) (mysql_global_variables_max_connections{namespace=~\"$instance_namespace\"})",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "mysql  disk reads vs writes",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(mysql_global_status_innodb_data_reads{namespace=~\"$instance_namespace\"}[1m]))",
     "legendFormat": "reads - {{ pod }}"
    },
    {
     "expr": "sum by (pod) (irate(mysql_global_status_innodb_data_writes{namespace=~\"$instance_namespace\"}[1m]))",
     "legendFormat": "write - {{ pod }}"
    }
   ]
  },
  {
   "title": "mysql network received vs sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(mysql_global_status_bytes_received{namespace=~\"$instance_namespace\"}[1m]))",
     "legendFormat": "received - {{ pod }}"
    },
    {
     "expr": "sum by (pod) (irate(mysql_global_status_bytes_sent{namespace=~\"$instance_namespace\"}[1m]))",
     "legendFormat": "sent - {{ pod }}"
    }
   ]
  },
  {
   "title": "Top Command Counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "max by (command) (rate(mysql_global_status_commands_total{namespace=~\"$instance_namespace\"}[$__rate_interval])) > 0",
     "legendFormat": "Com_{{ command }}"
    }
   ]
  },
  {
   "title": "MySQL File Openings",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (rate(mysql_global_status_opened_files{namespace=~\"$instance_namespace\"}[$__rate_interval]))",
     "legendFormat": "{{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL Open Files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (mysql_global_status_open_files{namespace=~\"$instance_namespace\"})",
     "legendFormat": "Open Files - {{ pod }}"
    },
    {
     "expr": "sum by (pod) (mysql_global_variables_open_files_limit{namespace=~\"$instance_namespace\"})",
     "legendFormat": "Open Files Limit - {{ pod }}"
    },
    {
     "expr": "sum by (pod) (mysql_global_status_innodb_num_open_files{namespace=~\"$instance_namespace\"})",
     "legendFormat": "InnoDB Open Files - {{ pod }}"
    }
   ]
  },
  {
   "title": "Storage Size",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 81 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max by (persistentvolumeclaim) (kubelet_volume_stats_used_bytes{namespace=\"$instance_namespace\"})",
     "legendFormat": "{{ persistentvolumeclaim }}"
    },
    {
     "expr": "max by (persistentvolumeclaim) (kubelet_volume_stats_capacity_bytes{namespace=\"$instance_namespace\"})",
     "legendFormat": "Limit {{ persistentvolumeclaim }}"
    }
   ]
  },
  {
   "title": "MySQL Slow Queries",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(mysql_global_status_slow_queries{namespace=~\"$instance_namespace\"}[1m]))",
     "legendFormat": "Slow Queries on {{ pod }}"
    }
   ]
  },
  {
   "title": "MySQL Aborted Connections",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum by (pod) (irate(mysql_global_status_aborted_connects{namespace=~\"$instance_namespace\"}[1m]))",
     "legendFormat": "Aborted Connects (attempts) on - {{ pod }}"
    },
    {
     "expr": "sum by (pod) (irate(mysql_global_status_aborted_clients{namespace=~\"$instance_namespace\"}[1m]))",
     "legendFormat": "Aborted Clients (timeout) on - {{ pod }}"
    }
   ]
  }
 ]
}