{
 "title": "VSHNMinIO",
 "description": "MinIO Grafana Dashboard",
 "tags": [
  "minio",
  "Appcat"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": {
     "query": "label_values(minio_cluster_health_status,cluster_id)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "text",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "# IMPORTANT\n\n<b>After each change please export this dashboard as JSON and update it in component-appcat repository</b>"
   }
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "time() - max(minio_node_process_starttime_seconds{cluster_id=\"$cluster\",cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Total S3 Ingress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (avg by (pod) (minio_s3_traffic_received_bytes{cluster_id=\"$cluster\",cluster_id=\"$cluster\",container=\"minio\"}))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total Online/Offline Drives",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 9, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "min(minio_cluster_drive_online_total{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "."
    },
    {
     "expr": "max(minio_cluster_drive_offline_total{job=~\"$scrape_jobs\"})",
     "legendFormat": "."
    }
   ]
  },
  {
   "title": "Capacity",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 14, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, sum(avg by (service) (minio_cluster_capacity_usable_total_bytes{cluster_id=\"$cluster\",container=\"minio\"})) by (service)) - topk(1, sum(avg by (service) (minio_cluster_capacity_usable_free_bytes{cluster_id=\"$cluster\",container=\"minio\"})) by (service))",
     "legendFormat": "Used"
    },
    {
     "expr": "topk(1, sum(avg by (service) (minio_cluster_capacity_usable_free_bytes{cluster_id=\"$cluster\",container=\"minio\"})) by (service)) ",
     "legendFormat": "Free"
    }
   ]
  },
  {
   "title": "Time Since Last Heal",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_heal_time_last_activity_nano_seconds{cluster_id=\"$cluster\",container=\"minio\"})"
    }
   ]
  },
  {
   "title": "Time Since Last Scan",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "max(minio_usage_last_activity_nano_seconds{cluster_id=\"$cluster\",container=\"minio\"})"
    }
   ]
  },
  {
   "title": "Total Online Servers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_nodes_online_total{cluster_id=\"$cluster\",container=\"minio\"})"
    }
   ]
  },
  {
   "title": "Total S3 Egress",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 4, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (service) (avg by (pod) (minio_s3_traffic_sent_bytes{cluster_id=\"$cluster\",container=\"minio\"}))\n"
    }
   ]
  },
  {
   "title": "Number of Buckets",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(minio_cluster_bucket_total{cluster_id=\"$cluster\",container=\"minio\"})"
    }
   ]
  },
  {
   "title": "Cluster Health Status",
   "type": "stat",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "minio_cluster_health_status{cluster_id=\"$cluster\",container=\"minio\"}",
     "legendFormat": "{{pod}} {{set}}"
    }
   ]
  },
  {
   "title": "Number of Objects",
   "type": "stat",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_object_total{cluster_id=\"$cluster\",container=\"minio\"})"
    }
   ]
  },
  {
   "title": "S3 API Request Rate",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 15, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service,api) (avg by (pod, api) ((increase(minio_s3_requests_total{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))))",
     "legendFormat": "{{service,api}}"
    }
   ]
  },
  {
   "title": "Object Size Distribution",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 9, "x": 15, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (range) (minio_cluster_objects_size_distribution{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(minio_node_process_cpu_total_seconds{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 15, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "label_replace(container_memory_rss{container=\"minio\"}, \"cluster_id\", \"$1\", \"$cluster\", \"^(.*)-user-workload$\")",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Data Usage Growth",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 15, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "max(minio_cluster_usage_total_bytes{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "Usage"
    }
   ]
  },
  {
   "title": "S3 API Egress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(minio_s3_traffic_sent_bytes{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "Data Sent [{{server}}]"
    }
   ]
  },
  {
   "title": "S3 API Ingress Rate ",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum by (service) (rate(minio_s3_traffic_received_bytes{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "Data Received [{{server}}]"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (5xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service,api) (increase(minio_s3_requests_5xx_errors_total{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "{{service,api}}"
    }
   ]
  },
  {
   "title": "Health Breakdown",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 16, "x": 0, "y": 54 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (service) (minio_cluster_health_erasure_set_online_drives{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "Online Drives"
    },
    {
     "expr": "avg by (service) (minio_cluster_health_erasure_set_read_quorum{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "Read Quorum"
    },
    {
     "expr": "avg by (service) (minio_cluster_health_erasure_set_write_quorum{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "Write Quorum"
    },
    {
     "expr": "avg by (service) (minio_cluster_health_erasure_set_healing_drives{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "Healing Drives"
    },
    {
     "expr": "avg by (service) (minio_cluster_health_erasure_set_status{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "Status"
    }
   ]
  },
  {
   "title": "S3 API Request Error Rate (4xx)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum by (service,api) (increase(minio_s3_requests_4xx_errors_total{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "{{service,api}}"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 61 },
   "targets": [
    {
     "expr": "avg by (pod) (minio_node_go_routine_total{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Open FDs ",
   "type": "timeseries",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 65 },
   "targets": [
    {
     "expr": "avg by (pod) (minio_node_file_descriptor_open_total{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Read, Write I/O",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(minio_node_io_rchar_bytes{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "Read [{{pod}}]"
    },
    {
     "expr": "avg by (pod) (rate(minio_node_io_wchar_bytes{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "Write [{{pod}}]"
    }
   ]
  },
  {
   "title": "Syscalls",
   "type": "timeseries",
   "description": "Number of online drives per MinIO Server",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(minio_node_syscall_read_total{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "Read Syscalls [{{pod}}]"
    },
    {
     "expr": "avg by (pod) (rate(minio_node_syscall_write_total{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "Write Syscalls [{{pod}}]"
    }
   ]
  },
  {
   "title": "Scanned Versions",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(minio_node_scanner_versions_scanned{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]"
    }
   ]
  },
  {
   "title": "File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg by (pod) (minio_node_file_descriptor_open_total{cluster_id=\"$cluster\",container=\"minio\"})",
     "legendFormat": "Open FDs [{{pod}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Started",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(minio_node_scanner_bucket_scans_started{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]"
    }
   ]
  },
  {
   "title": "Scanned Objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(minio_node_scanner_objects_scanned{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]"
    }
   ]
  },
  {
   "title": "Bucket Scans Finished",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(minio_node_scanner_bucket_scans_finished{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]"
    }
   ]
  },
  {
   "title": "Scanned Directories",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 91 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by (pod) (rate(minio_node_scanner_directories_scanned{cluster_id=\"$cluster\",container=\"minio\"}[$__rate_interval]))",
     "legendFormat": "[{{pod}}]"
    }
   ]
  }
 ]
}