= Install Exoscale Stack

This tutorial will guide you through the installation process of installing the following parts:

- A Crossplane provider to manage exoscale.com resources.
- A Crossplane composite (XRD) which serves as the user's "interface" (API) for ordering S3 buckets.
- A Crossplane composition that "implements" an XRD using the exoscale.com provider.

== Requirements

- `commodore`
- `vault`
- A Syn-enabled cluster with ArgoCD
- Vault instance to store credentials

== Preparation

. Prepare some variables
+
[source,bash]
----
export CLUSTER_ID=<the-cluster-id>
export TENANT_ID=<the-tenant-id>
----

. Login to Vault.
+
[source,bash]
----
export VAULT_ADDR=https://vault-prod.syn.vshn.net
vault login -method=oidc
----

. Create an Organization on Exoscale Portal.
. Create a new IAM key within the new project, give it a memorable name like `appcat-objects-${CLUSTER_ID}` and give it restricted access with only `sos` service.

. Save the token in Vault.
+
[source,bash]
----
parent="clusters/kv/${TENANT_ID}/${CLUSTER_ID}/appcat/objectstorage/provider-exoscale"
vault kv put "${parent}" access-key=<the-exoscale-access-key> secret-key=<the-exoscale-secret-key>
----

== Configuration

. Configure cluster catalog.
+
[source,yaml,attributes="verbatim"]
----
classes:
  - appcat.provider.exoscale <1>
  - appcat.provider.kubernetes <2>
  - appcat.composite.objectstorage <3>
  - appcat.composition.objectstorage.exoscale <4>
applications: <5>
  - pkg.appcat

parameters:
  packages:
    appcat:
      url: {page-origin-url}
      version: master <6>
      path: packages
----
<1> The config for the operator (provider) that talks to exoscale.com API.
<2> The config for the provider-kubernetes is required as a dependency.
<3> The XRD is configured in this package.
<4> The composition is configured in this package.
<5> We need to enable the packages as part of the applications.
    This gives us access to the provided classes.
<6> The version of the package (applies to all appcat packages!).

. Compile and push cluster catalog
