= Install Cloudscale Stack

This tutorial will guide you through the installation process of installing the following parts:

- A Crossplane provider to manage cloudscale.ch resources.
- A Crossplane composite (XRD) which serves as the user's "interface" (API) for ordering S3 buckets.
- A Crossplane composition that "implements" an XRD using the cloudscale.ch provider.

== Requirements

- `commodore`
- `vault`
- A Syn-enabled cluster with ArgoCD
- Vault instance to store credentials

== Preparation

. Prepare some variables
+
[source,bash]
----
export CLUSTER_ID=<the-cluster-id>
export TENANT_ID=<the-tenant-id>
----

. Login to Vault.
+
[source,bash]
----
export VAULT_ADDR=https://vault-prod.syn.vshn.net
vault login -method=oidc
----

. Create a project in control.cloudscale.ch.
. Create a new API token within the new project, give it a memorable name like `appcat-objects-${CLUSTER_ID}` and write access.

. Save the token in Vault.
+
[source,bash]
----
parent="clusters/kv/${TENANT_ID}/${CLUSTER_ID}/appcat/objectstorage/provider-cloudscale"
vault kv patch "${parent}" token=<the-cloudscale-token>
----

== Configuration

. Configure cluster catalog.
+
[source,yaml,attributes="verbatim"]
----
classes:
  - appcat.provider.cloudscale <1>
  - appcat.composite.objectstorage <2>
  - appcat.composition.objectstorage.cloudscale <3>
applications: <4>
  - pkg.appcat.provider.cloudscale
  - pkg.appcat.composite.objectstorage
  - pkg.appcat.composition.objectstorage.cloudscale

parameters:
  packages:
    appcat:
      version: master <5>
      url: {page-origin-url}
      path: packages
----
<1> The config for the operator (provider) that talks to cloudscale.ch API.
<2> The XRD is configured in this package.
<3> The composition is configured in this package.
<4> We need to enable the packages as part of the applications.
    This gives us access to the provided classes.
<5> The version of the package (applies to all appcat packages!).

. Compile and push cluster catalog
