= Component Parameters

The parent key for all of the following parameters is `appcat`.


== `images`
[horizontal]
type:: dict
default:: https://github.com/vshn/component-appcat/blob/master/class/defaults.yml[See `class/defaults.yml`]

This parameter allows selecting the Docker images to us.
Each image is specified using keys `registry`, `repository` and `tag`.
This structure allows easily injecting a registry mirror, if required.


== `apiserver`
[horizontal]
type:: dict
reference:: xref:references/appcat-apiserver.adoc[See API Server parameters]

This parameter allows configuring https://github.com/vshn/appcat[the AppCat API Server].


== `slos`
[horizontal]
type:: dict
reference:: xref:references/slo-parameters.adoc[See SLO parameters]

This parameter allows configuring SLOs for AppCat.

== `providers`


=== `providers.cloudscale`
[horizontal]
type:: dict
reference:: xref:references/provider-cloudscale.adoc[See provider parameters]


This parameter allows configuring https://github.com/vshn/provider-cloudscale[the provider cloudscale].


=== `providers.exoscale`
[horizontal]
type:: dict
reference:: xref:references/provider-exoscale.adoc[See provider parameters]


This parameter allows configuring https://github.com/vshn/provider-exoscale[the provider exoscale].


=== `providers.kubernetes`
[horizontal]
type:: dict
reference:: xref:references/provider-kubernetes.adoc[See provider parameters]


This parameter allows configuring https://github.com/crossplane-contrib/provider-kubernetes[the provider kubernetes].


== `services`

=== `services.exoscale`
[horizontal]
type:: dict
reference:: xref:references/services-exoscale.adoc[See service parameters]

This parameter allows enabling and configuring exoscale specific AppCat services.

=== `services.generic`
[horizontal]
type:: dict

The `generic` parameter contains configuration for AppCat services that aren't specific to one provider, but are implemented by multiple different providers.

=== `services.generic.objectstorage`
[horizontal]
type:: dict
reference:: xref:references/service-objectstorage.adoc[See service parameters]

This parameter allows enabling and configuring the generic objectstorage AppCat service.
