= Component Parameters

The parent key for all of the following parameters is `appcat`.


== `images`
[horizontal]
type:: dict
default:: https://github.com/vshn/component-appcat/blob/master/class/defaults.yml[See `class/defaults.yml`]

This parameter allows selecting the Docker images to us.
Each image is specified using keys `registry`, `repository` and `tag`.
This structure allows easily injecting a registry mirror, if required.

== `appuioManaged`
[horizontal]
type:: bool
default:: true

Determines if the cluster is APPUiO Managed or APPUiO Cloud.

== `tenantID`
[horizontal]
type:: string
default:: ${cluster:tenant}

The tenant ID that should get hardcoded into the billing query.

== `namespace`

[horizontal]
type:: string
default:: `syn-appcat`

The namespace in which to deploy AppCat resources.

== `namespaceLabels`

[horizontal]
type:: dict
default:: `{}`

Additional labels to add to the created namespace.

== `namespaceAnnotations`

[horizontal]
type:: dict
default:: `{}`

Additional annotations to add to the created namespace.


== `apiserver`
[horizontal]
type:: dict
reference:: xref:references/appcat-apiserver.adoc[See API Server parameters]

This parameter allows configuring https://github.com/vshn/appcat[the AppCat API Server].


== `slos`
[horizontal]
type:: dict
reference:: xref:references/slo-parameters.adoc[See SLO parameters]

This parameter allows configuring SLOs for AppCat.

== `providers`
Each provider's manifests are generated by a generic jsonnet function. So each of them have common parameters.

=== `enabled`
type:: boolean
default:: `true|false`
required:: true

Specifies if this provider should be enabled or not.

=== `apiVersion`
type:: string
default:: `N/A`
required:: true

Define the apiVersion of the providers `providerConf` kind. Can vary for each provider.

=== `connectionSecretNamespace`
type:: string
default:: `${appcat:crossplane:namespace}`
required:: false

Specify separate namespace where the provider saves the connection secrets.

=== `namespace`
type:: string
default:: `${appcat:crossplane:namespace}`
required:: true

Namespace where the provider should get installed.

=== `credentials`
type:: object
default:: `null`
required:: false

Contents of the secret containing credentials to connect to the provider's external systems. E.g. another cloud or another Kubernetes cluster.
There are some subfields that need to be specifed.

==== `name`
type:: string
default:: `""`
required:: true

The name of the secret.

==== `namespace`
type:: string
default:: `""`
required:: true

The namespace of the secret.

==== `data`
type:: map
default:: `{}`
required:: true

The contents of the `data` map of the secret.

=== `spec`
type:: object
default:: `{}`
required:: true

Overrides for the `spec` part of the crossplane package. Usually used to set the actual image to be used.

=== `runtimeConfig`
type:: object
default:: `{}`
required:: true

Overrides the deployment's configuration. Usually used to set the `serviceAccountName` to match the generated RBAC rules.

=== `defaultProviderConfig`
type:: object
default:: `{}`
required:: false

Sets the contents of the default `providerConfig` object that gets deployed to the clusters. This `providerConfig` will have the same name as the provider.

=== `additionalProviderConfigs`
type:: array
default:: `[]`
required:: false

Array of additional `providerConfigs`. Should contain the name and the spec of the 'providerConfig' objects to be generated.

==== `name`
type:: string
default:: `""`
required:: true

Name of the `providerConfig`.

==== `spec`
type:: object
default:: `{}`
required:: true

`spec` of the `providerConfig`. It needs to be the full spec, there are no defaults injected.

== `services`

=== `services.controlNamespace`
type:: string
default:: `'appcat-control'`

Name of the additional namespace for appcat that's needed for backups and maintenance

=== `services.exoscale`
[horizontal]
type:: dict
reference:: xref:references/services-exoscale.adoc[See service parameters]

This parameter allows enabling and configuring exoscale specific AppCat services.

=== `services.generic`
[horizontal]
type:: dict

The `generic` parameter contains configuration for AppCat services that aren't specific to one provider, but are implemented by multiple different providers.

=== `services.generic.objectstorage`
[horizontal]
type:: dict
reference:: xref:references/service-objectstorage.adoc[See service parameters]

This parameter allows enabling and configuring the generic objectstorage AppCat service.

== `billing`
[horizontal]
type:: dict
reference:: xref:references/appcat-billing.adoc[See AppCat billing parameters]

This parameter allows configuring billing for AppCat.

== `clusterManagementSystem`
[horizontal]
type:: dict

Specifies if the setup runs in converged mode or in split mode.

=== `controlPlaneCluster`
[horizontal]
type:: bool
default:: true

Configures the cluster to be a control plane.

=== `serviceCluster`
[horizontal]
type:: bool
default:: true

Configures the cluster to be a service cluster.

=== `controlPlaneKubeconfig`
[horizontal]
type:: string
default:: ""

Configures the kubeconfig to use to connect back to the control plane cluster.
The kubeconfig is only used if the configuration is not in converged mode.
It has to be created beforehand with the proper RBAC.

== `deploymentManagementSystem`
[horizontal]
type:: dict

Controls aspects of the deployment via comp-function revisions.

=== `hotfix`
[horizontal]
type:: bool
default:: false

Defines if all instances should instantly be switched over to the new release or not. This will generate a job that will run the rollout.

=== `enabled`
[horizontal]
type:: bool
default:: true

Specifies if the system should be enabled or not. If it's disabled all changes will be rolled out immediately.

=== `additionalFunctionBranches`
[horizontal]
type:: array
default:: []

Specify additional function branches that should be deployed. Mostly used to test various versions at the same time on the lab.
