= VSHN Services

The parent key for all of the following parameters is `appcat.services.vshn`.

[IMPORTANT]
====
If you enable any of the VSHN service, make sure that the necessary providers are deployed.
Either by enabling it in `appcat.providers` or separately from this component.

====

=== `enabled`
[horizontal]
type:: bool
default:: `false`

If VSHN services should be available at all.
When set to false no VSHN services will be deployed, even if a specific service was enabled.

=== `secretNamespace`
[horizontal]
type:: string
default:: `${crossplane:namespace}`

In which namespace an XR's connection secret is written to.

Defaults to the crossplane namespace.


== `postgres`
[horizontal]
type:: dict

Configuration option for VSHN PostgreSQL.
You have to option to enable or disable it through the `enabled` parameter and can set the `secretNamespace` and `providerSecretNamespace`.

It's enabled by default and use the top level defined namespaces for `secretNamespace` and `providerSecretNamespace`.


=== `postgres.enableNetworkPolicy`
type:: bool
default:: `true`

Whether to enable NetworkPolicy in the PostgreSQL instance namespace. This allows to establish connections from claim's namespace to the PostgreSQL instance.

=== `postgres.controlNamespace`
type:: string
default:: `'appcat-control'`

Name of the additional namespace that's needed to the backup copy job.

=== `postgres.bucket_region`
type:: string
default:: `''`

Bucket region, required for xObjectBucket and PostreSQL managed by VSHN backup, should be cloud specific.

.Examples
* Cloudscale
** 'lpg'
* Exoscale
** 'ch-gva-2'

=== `postgres.bucket_endpoint`
type:: string
default:: `''`

Bucket endpoint, required for xObjectBucket and PostreSQL managed by VSHN backup, should be cloud specific.

.Examples
* Cloudscale
** 'https://objects.lpg.cloudscale.ch'
* Exoscale
** 'https://sos-ch-gva-2.exo.io'

=== `postgres.plan`
type:: dict

A dict of plans for PostgreSQL by VSHN.

The key is the name of the plan.
You can configure the CPU request through `size.cpu`, memory through `size.memory`, and disk size through `size.disk`.
You can also set a node selector through `scheduling.nodeSelector`.

There is also the option to specify a note in `note`, which will be added to the description of the field in the CRD.

.Examples
[source,yaml]
----
plans:
  standard-2:
    size:
      cpu: "400m"
      memory: "1728Mi"
      disk: 20Gi
  standard-4:
    size:
      cpu: "900m"
      memory: "3776Mi"
      disk: 40Gi
  standard-8:
    enabled: false
  plus-4:
    size: ${appcat:services:vshn:postgres:plans:standard-4:size}
    scheduling:
      nodeSelector:
        appuio.io/node-class: "plus"
    note: "Will be scheduled on APPUiO Cloud plus nodes"
----

=== `postgres.defaultPlan`
type:: string
default:: `standard-2`

The default plan used for PostgreSQL by VSHN, if the service user doesn't specify a plan.

== `redis`
[horizontal]
type:: dict

Configuration option for VSHN Redis.
You have to option to enable or disable it through the `enabled` parameter and can set the `secretNamespace` and `providerSecretNamespace`.

It's enabled by default and use the top level defined namespaces for `secretNamespace` and `providerSecretNamespace`.


=== `redis.enableNetworkPolicy`
type:: bool
default:: `true`

Whether to enable NetworkPolicy in the Redis instance namespace. This allows to establish connections from claim's namespace to the Redis instance.
