= AppCat SLO Parameters

The parent key for all the following parameters is `appcat.slos`.

== `enabled`
[horizontal]
type:: bool
default:: `true`

If the SLOs should be enabled in general.

== `namespace`
[horizontal]
type:: string
default:: `appcat-slos`

A namespace where all SLO related resources will be deployed to, including the SLI Exporter.
The namespace will be created and managed by this component.

== `sli_exporter.resources`
[horizontal]
type:: dict

The resource requests and limits for the SLI Exporter.

== `sli_exporter.kustomize_input`
[horizontal]
type:: dict

The input passed to the Kustomize renderer.
See https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/[the Kustomization File] for all available options.

== `alerting.labels`
[horizontal]
type:: dict

Labels that will be added to any SLO alerts.

== `alerting.page_labels`
[horizontal]
type:: dict

Labels that will be added to any critical SLO alerts.
`page_alerts` are alerts are critical alerts for a high burn rate that require immediate attention.

== `alerting.tickt_labels`
[horizontal]
type:: dict

Labels that will be added to any non-crtiical SLO alerts.
`ticket_alerts` are alerts for an elevated burn rate that might require attention, but aren’t urgent.

== `vshn.postgres.uptime`

Configuration of the PostgreSQL by VSHN uptime SLO.

=== `vshn.postgres.uptime.objective`
[horizontal]
type:: float
default:: 99.9

The SLO objective in percentage between 0-100.

=== `vshn.postgres.uptime.alerting.page_alert`
[horizontal]
type:: dict

The alert configuration for `page_alerts`.
Can be used to add additional labels or annotations through `labels` or `annotations` key, disable the alert through the `disable` key, or delay emitting the alert through the `for` key.

=== `vshn.postgres.uptime.alerting.ticket_alert`
[horizontal]
type:: dict

The alert configuration for `ticket_alert`.
Can be used to add additional labels or annotations through `labels` or `annotations` key, disable the alert through the `disable` key, or delay emitting the alert through the `for` key.

.Example

[source,yaml]
----
vshn:
  postgres:
    uptime:
      objective: 81.9 <1>
      alerting:
        page_alert:
          labels: <2>
            foo: bar
          for: 13m <3>
        ticket_alert:
          annotations: <4>
            please: ignore
----
<1> Reduces the objective to 81.9%
<2> Adds the label `foo: bar` to all page alerts
<3> Only fires page alerts if they are pending for 13 minutes
<4> Adds annotation `please: ignore` to all ticket alerts

== `sla_reporter`

Configuration options for the monthly SLA report generator.

=== `sla_reporter.enabled`
[horizontal]
type:: boolean
default:: false

Enables or disables the monthly reporter cronjob.

=== `sla_reporter.resources`
[horizontal]
type:: dict

The resource requests and limits for the SLA Reporter.

=== `sla_reporter.schedule`
[horizontal]
type:: string
default:: "0 9 1 * *"

Cron schedule when the SLA Reporter should run.

=== `sla_reporter.bucket_region`
[horizontal]
type:: dict
default:: lpg

The region in which the bucket that stores the reports should be provisioned.

=== `sla_reporter.slo_mimir_endpoint`
[horizontal]
type:: dict
default:: http://vshn-appuio-mimir-query-frontend.vshn-appuio-mimir.svc.cluster.local:8080/prometheus

Endpoint for the Prometheus compatible data source.

=== `sla_reporter.mimir_organization`
[horizontal]
type:: dict
default:: appuio-managed-openshift-metrics

Organization header needed to query Mimir data sources.
